<a href="https://colab.research.google.com/github/Antony6001/mini-project-DS/blob/main/json_file_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import json

In [ ]:
df=pd.read_json("/content/orders.json")

In [ ]:
with open("/content/orders.json")as f:
  df=json.load(f)

In [ ]:
df = pd.json_normalize(df)
print(df.head())

                               order_id          restaurant_name  order_date  \
0  8174c2af-07a4-4837-9068-1169d963e36e           TBC Sky Lounge  2025-05-06
1  0f9ddb57-4632-4a9f-9afe-1d2e41b94e32  KC Das - Sweet Paradise  2026-01-08
2  099deda6-8c53-41cb-abf8-00126e6b2643        Hotel Kadamba Veg  2026-01-22
3  94a6ba27-d6ef-4d10-a026-ac0c0afa8505            Cafe Srinidhi  2025-11-10
4  216f3ec7-80a9-4d95-872f-715c37163b6d                   Pebble  2025-12-22

   order_value discount_used payment_method
0       201.87            No           Card
1      1392.27            No           Cash
2      1358.35           Yes            UPI
3       782.37            No            UPI
4      1551.09           Yes            UPI

In [ ]:
df.shape

(25000, 6)

In [ ]:
df.columns

Index(['order_id', 'restaurant_name', 'order_date', 'order_value',
       'discount_used', 'payment_method'],
      dtype='object')

In [ ]:
df.order_id.value_counts()

order_id
af55e28b-27fc-49fc-bdb0-b297999dd152    1
8174c2af-07a4-4837-9068-1169d963e36e    1
0f9ddb57-4632-4a9f-9afe-1d2e41b94e32    1
099deda6-8c53-41cb-abf8-00126e6b2643    1
94a6ba27-d6ef-4d10-a026-ac0c0afa8505    1
                                       ..
00a0c73e-b797-4322-afc4-6199d5f68ce9    1
11c7ea0f-cafa-4b63-a14e-7129fa934e95    1
28bcfd85-fd84-458c-851b-60311c625d01    1
25b2d40b-35b3-40f7-9cbe-37bf690db837    1
e44b23ce-6d29-4c09-9eac-9d4f24f56fd9    1
Name: count, Length: 25000, dtype: int64

In [ ]:
df.order_id.isnull().sum()

np.int64(0)

In [ ]:
df.restaurant_name

0                 TBC Sky Lounge
1        KC Das - Sweet Paradise
2              Hotel Kadamba Veg
3                  Cafe Srinidhi
4                         Pebble
                  ...
24995                   Carnatic
24996         Reddy's Restaurant
24997       BTM Bawarchi Biryani
24998                   Nite Out
24999                  Zee5 Loft
Name: restaurant_name, Length: 25000, dtype: object

In [ ]:
df.restaurant_name = df.restaurant_name.str.lower()

In [ ]:
df.restaurant_name=df.restaurant_name.str.strip()

In [ ]:
df.restaurant_name=df.restaurant_name.str.replace("-","")

In [ ]:
df['restaurant_name'] = df['restaurant_name'].str.replace(r'[^a-zA-Z\s]', '', regex=True)

In [ ]:
df.restaurant_name.value_counts()

restaurant_name
khan saheb grills and rolls                25
kesar sweet shop and fast food             20
andhra grills                              19
cake cafe                                  19
kkr foodies                                19
                                           ..
24@43 - the oterra                          1
intriicake                                  1
swathi maharaja                             1
the hub & the bar - hotel ramada encore     1
the barn - bar & kitchen                    1
Name: count, Length: 3152, dtype: int64

In [ ]:
df.restaurant_name.isnull().sum()

np.int64(0)

In [ ]:
df.restaurant_name.unique()

array(['tbc sky lounge', 'kc das - sweet paradise', 'hotel kadamba veg',
       ..., 'uptown sliders & shakes', 'asha sweets center',
       'biryani treats'], dtype=object)

In [ ]:
df.order_date

0        2025-05-06
1        2026-01-08
2        2026-01-22
3        2025-11-10
4        2025-12-22
            ...
24995    2025-11-24
24996    2025-06-24
24997    2025-12-04
24998    2025-09-21
24999    2025-08-07
Name: order_date, Length: 25000, dtype: object

In [ ]:
import datetime

In [ ]:
df['order_date']=pd.to_datetime(df['order_date'])

In [ ]:
df['order_date']=pd.to_datetime(df['order_date'],errors='coerce')

In [ ]:
df['order_date'].value_counts()

order_date
2025-05-16    113
2026-01-08    112
2025-07-26    105
2025-11-05    105
2026-01-01    105
             ...
2025-09-16     65
2025-08-26     65
2026-02-23     64
2025-06-07     64
2025-11-22     55
Name: count, Length: 301, dtype: int64

In [ ]:
df['order_date'].isnull().sum()

np.int64(0)

In [ ]:
df.columns

Index(['order_id', 'restaurant_name', 'order_date', 'order_value',
       'discount_used', 'payment_method'],
      dtype='object')

In [ ]:
df['order_date'].dtype

dtype('<M8[ns]')

In [ ]:
df['order_value']

0         201.87
1        1392.27
2        1358.35
3         782.37
4        1551.09
          ...
24995    1254.91
24996     760.39
24997     707.99
24998     724.29
24999     905.00
Name: order_value, Length: 25000, dtype: float64

In [ ]:
df.order_value.value_counts()

order_value
418.46     4
490.43     4
1092.84    4
553.52     4
466.45     3
          ..
236.55     1
624.26     1
890.83     1
498.75     1
1762.82    1
Name: count, Length: 23212, dtype: int64

In [ ]:
df.order_value.isnull().sum()

np.int64(0)

In [ ]:
df.order_value.describe()

count    25000.000000
mean       986.081873
std        472.948544
min        150.050000
25%        589.602500
50%        966.475000
75%       1344.772500
max       1999.840000
Name: order_value, dtype: float64

In [ ]:
df.discount_used

0         No
1         No
2        Yes
3         No
4        Yes
        ...
24995     No
24996     No
24997    Yes
24998    Yes
24999     No
Name: discount_used, Length: 25000, dtype: object

In [ ]:
df.discount_used.value_counts()

discount_used
No     12509
Yes    12491
Name: count, dtype: int64

In [ ]:
df.discount_used.unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
df.discount_used.isnull().sum()

np.int64(0)

In [ ]:
df.discount_used=df.discount_used.str.lower()

In [ ]:
df.discount_used

0         no
1         no
2        yes
3         no
4        yes
        ...
24995     no
24996     no
24997    yes
24998    yes
24999     no
Name: discount_used, Length: 25000, dtype: object

In [ ]:
df.payment_method

0        Card
1        Cash
2         UPI
3         UPI
4         UPI
         ...
24995     UPI
24996    Card
24997    Card
24998    Card
24999     UPI
Name: payment_method, Length: 25000, dtype: object

In [ ]:
df.payment_method.value_counts()

payment_method
Cash    8384
Card    8364
UPI     8252
Name: count, dtype: int64

In [ ]:
df.payment_method.unique()

array(['Card', 'Cash', 'UPI'], dtype=object)

In [ ]:
df.payment_method=df.payment_method.str.lower()

In [ ]:
df.payment_method.isnull().sum()

np.int64(0)

In [ ]:
df.payment_method.unique()

array(['card', 'cash', 'upi'], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         25000 non-null  object
 1   restaurant_name  25000 non-null  object
 2   order_date       25000 non-null  datetime64[ns]
 3   order_value      25000 non-null  float64
 4   discount_used    25000 non-null  object
 5   payment_method   25000 non-null  object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 1.1+ MB

In [ ]:
df.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,tbc sky lounge,2025-05-06,201.87,no,card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,kc das - sweet paradise,2026-01-08,1392.27,no,cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,hotel kadamba veg,2026-01-22,1358.35,yes,upi
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,cafe srinidhi,2025-11-10,782.37,no,upi
4,216f3ec7-80a9-4d95-872f-715c37163b6d,pebble,2025-12-22,1551.09,yes,upi

In [ ]:
df.describe()

                       order_date   order_value
count                       25000  25000.000000
mean   2025-09-26 18:27:31.968000    986.081873
min           2025-04-29 00:00:00    150.050000
25%           2025-07-14 00:00:00    589.602500
50%           2025-09-27 00:00:00    966.475000
75%           2025-12-12 00:00:00   1344.772500
max           2026-02-23 00:00:00   1999.840000
std                           NaN    472.948544

In [ ]:
df.restaurant_name

0                tbc sky lounge
1        kc das  sweet paradise
2             hotel kadamba veg
3                 cafe srinidhi
4                        pebble
                  ...
24995                  carnatic
24996         reddys restaurant
24997      btm bawarchi biryani
24998                  nite out
24999                  zee loft
Name: restaurant_name, Length: 25000, dtype: object

In [ ]:
import os

In [ ]:
df.to_csv("orders.csv")