<a href="https://colab.research.google.com/github/Antony6001/mini-project-DS/blob/main/uber_eats_bangalore_mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
df=pd.read_csv('/content/Uber_Eats_data.csv')

In [ ]:
df.shape

(23193, 13)

In [ ]:
df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [ ]:
df['name'] = df['name'].str.encode('latin1', errors='ignore').str.decode('utf-8', errors='ignore')

In [ ]:
import re

df['name'] = df['name'].apply(lambda x: re.sub(r'[^a-zA-Z0-9 &]', '', x))

In [ ]:
df.name.unique()

array(['Jalsa', 'Spice Elephant', 'San Churro Cafe', ..., 'TukTuk',
       'Chime  Sheraton Grand Bengaluru Whitefield Hotel &',
       'Fujian Express'], dtype=object)

In [ ]:
df.name=df.name.str.lower().str.replace(' ','_')

In [ ]:
df.online_order.dtype

dtype('O')

In [ ]:
df.online_order.value_counts()

online_order
Yes    16358
No      6835
Name: count, dtype: int64

In [ ]:
sum(df.online_order.isnull())

0

In [ ]:
df.online_order

0        Yes
1        Yes
2        Yes
3         No
4         No
        ...
23188    Yes
23189     No
23190     No
23191     No
23192     No
Name: online_order, Length: 23193, dtype: object

In [ ]:
df.online_order.unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
df.online_order=df.online_order.str.lower().str.replace(' ','_')

In [ ]:
df.book_table.value_counts()

book_table
No     17071
Yes     6122
Name: count, dtype: int64

In [ ]:
df.book_table.isnull().sum()

np.int64(0)

In [ ]:
df.book_table=df.book_table.str.lower().str.replace(' ','_')

In [ ]:
df.rate.isnull().sum()

np.int64(0)

In [ ]:
df.rate.unique()

array(['4.1/5', '3.8/5', '3.7/5', '4.6/5', '4.0/5', '4.2/5', '3.9/5',
       '3.0/5', '3.6/5', '2.8/5', '4.4/5', '3.1/5', '4.3/5', '2.6/5',
       '3.3/5', '3.5/5', '3.8 /5', '3.2/5', '4.5/5', '2.5/5', '2.9/5',
       '3.4/5', '2.7/5', '4.7/5', 'NEW', '2.4/5', '2.2/5', '2.3/5',
       '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5', '2.9 /5',
       '2.7 /5', '2.5 /5', '2.6 /5', '4.5 /5', '4.3 /5', '3.7 /5',
       '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5', '3.4 /5', '3.6 /5',
       '3.3 /5', '4.6 /5', '4.9 /5', '3.2 /5', '3.0 /5', '2.8 /5',
       '3.5 /5', '3.1 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5',
       '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [ ]:
import ast

In [ ]:
df['rate']=df['rate'].replace(['NEW',None])

/tmp/ipykernel_18690/1447076736.py:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df['rate']=df['rate'].replace(['NEW',None])

In [ ]:
df.rate.unique()

array(['4.1/5', '3.8/5', '3.7/5', '4.6/5', '4.0/5', '4.2/5', '3.9/5',
       '3.0/5', '3.6/5', '2.8/5', '4.4/5', '3.1/5', '4.3/5', '2.6/5',
       '3.3/5', '3.5/5', '3.8 /5', '3.2/5', '4.5/5', '2.5/5', '2.9/5',
       '3.4/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5', '4.8/5',
       '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5', '2.9 /5', '2.7 /5',
       '2.5 /5', '2.6 /5', '4.5 /5', '4.3 /5', '3.7 /5', '4.4 /5',
       '4.9/5', '2.1/5', '2.0/5', '1.8/5', '3.4 /5', '3.6 /5', '3.3 /5',
       '4.6 /5', '4.9 /5', '3.2 /5', '3.0 /5', '2.8 /5', '3.5 /5',
       '3.1 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5', '2.1 /5',
       '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [ ]:
df['rate']=df['rate'].str.replace('/5','').astype(float)

In [ ]:
df.rate

0        4.1
1        4.1
2        3.8
3        3.7
4        3.8
        ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: rate, Length: 23193, dtype: float64

In [ ]:
df.votes

0        775
1        787
2        918
3         88
4        166
        ...
23188    128
23189     77
23190    161
23191     81
23192    236
Name: votes, Length: 23193, dtype: int64

In [ ]:
df.votes.isnull().sum()

np.int64(0)

In [ ]:
df.votes.dtype

dtype('int64')

In [ ]:
df.votes.unique()

array([ 775,  787,  918, ..., 4957, 2382,  843])

In [ ]:
df.phone

0          080 42297555\r\n+91 9743772233
1                            080 41714161
2                          +91 9663487993
3                          +91 9620009302
4        +91 8026612447\r\n+91 9901210005
                       ...
23188      +91 7625087121\n+91 8050587483
23189                        080 49435000
23190        080 39451000\n+91 8884038484
23191                        080 65951222
23192                        080 49652769
Name: phone, Length: 23193, dtype: object

In [ ]:
df.phone.dtype

dtype('O')

In [ ]:
df.phone.isnull().sum()

np.int64(0)

In [ ]:
df.phone=df.phone.str.replace(r'\D','',regex=True)

In [ ]:
df.phone.unique()

array(['08042297555919743772233', '08041714161', '919663487993', ...,
       '919535948061', '917760075458919591852291', '08065951222'],
      dtype=object)

In [ ]:
df['mobile'] = df['phone'].str[-10:]

In [ ]:
df['landline'] = df['phone'].str[:-10]

In [ ]:
df['landline'] = df['landline'].str.replace('^91', '', regex=True)

In [ ]:
df['mobile'] = df['phone'].str.extract(r'(\d{10})$')

In [ ]:
df.mobile.isnull().sum()

np.int64(0)

In [ ]:
df.landline.isnull().sum()

np.int64(0)

In [ ]:

df.mobile=df.mobile.astype(int)

In [ ]:
df.landline.dtype

dtype('O')

In [ ]:
df['landline'] = pd.to_numeric(df['landline'], errors='coerce')

In [ ]:
df.landline.unique()

array([8.04229756e+11, 0.00000000e+00,            nan, ...,
       9.66346840e+10, 8.06122472e+11, 7.76007546e+11])

In [ ]:
df.landline.unique()

array([8.04229756e+11, 0.00000000e+00,            nan, ...,
       9.66346840e+10, 8.06122472e+11, 7.76007546e+11])

In [ ]:
df.landline.unique()

array([8.04229756e+11, 0.00000000e+00,            nan, ...,
       9.66346840e+10, 8.06122472e+11, 7.76007546e+11])

In [ ]:
df.landline.dtype

dtype('float64')

In [ ]:
df = df.drop('landline', axis=1)

In [ ]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'listed_in(type)', 'listed_in(city)',
       'mobile'],
      dtype='object')

In [ ]:
df.location

0                      Banashankari
1                      Banashankari
2                      Banashankari
3                      Banashankari
4                      Basavanagudi
                    ...
23188                    Whitefield
23189                    Whitefield
23190                    Whitefield
23191                    Whitefield
23192    ITPL Main Road, Whitefield
Name: location, Length: 23193, dtype: object

In [ ]:
df.location.unique()

array(['Banashankari', 'Basavanagudi', 'Jayanagar', 'Kumaraswamy Layout',
       'Rajarajeshwari Nagar', 'Mysore Road', 'Uttarahalli',
       'South Bangalore', 'Vijay Nagar', 'Bannerghatta Road', 'JP Nagar',
       'BTM', 'Wilson Garden', 'Koramangala 5th Block', 'Shanti Nagar',
       'Richmond Road', 'City Market', 'Bellandur', 'Sarjapur Road',
       'Marathahalli', 'HSR', 'Old Airport Road', 'Indiranagar',
       'Koramangala 1st Block', 'East Bangalore', 'MG Road',
       'Brigade Road', 'Lavelle Road', 'Church Street', 'Ulsoor',
       'Residency Road', 'Shivajinagar', 'Infantry Road',
       'St. Marks Road', 'Cunningham Road', 'Race Course Road', 'Domlur',
       'Koramangala 8th Block', 'Frazer Town', 'Ejipura', 'Vasanth Nagar',
       'Jeevan Bhima Nagar', 'Old Madras Road', 'Commercial Street',
       'Koramangala 6th Block', 'Majestic', 'Langford Town',
       'Koramangala 7th Block', 'Brookefield', 'Whitefield',
       'ITPL Main Road, Whitefield', 'Varthur Main Road, Whitefield',
       'Koramangala 2nd Block', 'Koramangala 3rd Block',
       'Koramangala 4th Block', 'Koramangala', 'Bommanahalli',
       'Hosur Road', 'Seshadripuram', 'Electronic City', 'Banaswadi',
       'North Bangalore', 'RT Nagar', 'Kammanahalli', 'Hennur',
       'HBR Layout', 'Kalyan Nagar', 'Thippasandra', 'CV Raman Nagar',
       'Kaggadasapura', 'Kanakapura Road', 'Nagawara', 'Rammurthy Nagar',
       'Sankey Road', 'Central Bangalore', 'Malleshwaram',
       'Sadashiv Nagar', 'Basaveshwara Nagar', 'Rajajinagar',
       'New BEL Road', 'West Bangalore', 'Yeshwantpur', 'Sanjay Nagar',
       'Sahakara Nagar', 'Jalahalli', 'Yelahanka', 'Magadi Road',
       'KR Puram'], dtype=object)

In [ ]:
df.location=df.location.str.lower().str.replace(' ','_')

In [ ]:
df.location

0                      banashankari
1                      banashankari
2                      banashankari
3                      banashankari
4                      basavanagudi
                    ...
23188                    whitefield
23189                    whitefield
23190                    whitefield
23191                    whitefield
23192    itpl_main_road,_whitefield
Name: location, Length: 23193, dtype: object

In [ ]:
df.location.value_counts()

location
koramangala_5th_block    1783
btm                      1456
indiranagar              1350
hsr                      1162
jayanagar                1037
                         ...
kanakapura_road             2
west_bangalore              2
yelahanka                   2
magadi_road                 2
kr_puram                    1
Name: count, Length: 88, dtype: int64

In [ ]:
df.location.describe()

count                     23193
unique                       88
top       koramangala_5th_block
freq                       1783
Name: location, dtype: object

In [ ]:

df.location

0                      banashankari
1                      banashankari
2                      banashankari
3                      banashankari
4                      basavanagudi
                    ...
23188                    whitefield
23189                    whitefield
23190                    whitefield
23191                    whitefield
23192    itpl_main_road,_whitefield
Name: location, Length: 23193, dtype: object

In [ ]:
df.location.isnull().sum()

np.int64(0)

In [ ]:
df.rest_type

0              Casual Dining
1              Casual Dining
2        Cafe, Casual Dining
3                Quick Bites
4              Casual Dining
                ...
23188     Bar, Casual Dining
23189       Fine Dining, Bar
23190     Casual Dining, Bar
23191     Casual Dining, Bar
23192                    Bar
Name: rest_type, Length: 23193, dtype: object

In [ ]:
df.rest_type=df.rest_type.str.lower().str.replace(' ','')

In [ ]:
df.rest_type

0             casualdining
1             casualdining
2        cafe,casualdining
3               quickbites
4             casualdining
               ...
23188     bar,casualdining
23189       finedining,bar
23190     casualdining,bar
23191     casualdining,bar
23192                  bar
Name: rest_type, Length: 23193, dtype: object

In [ ]:
df.rest_type.unique()

array(['casualdining', 'cafe,casualdining', 'quickbites',
       'casualdining,cafe', 'cafe', 'quickbites,cafe', 'delivery',
       'dessertparlor', 'pub', 'beverageshop', 'bar', 'takeaway,delivery',
       'foodtruck', 'quickbites,dessertparlor', 'pub,casualdining',
       'casualdining,bar', 'bakery', 'sweetshop',
       'dessertparlor,beverageshop', 'beverageshop,quickbites',
       'microbrewery,casualdining', 'sweetshop,quickbites', 'lounge',
       'foodcourt', 'cafe,bakery', 'microbrewery', 'kiosk', 'pub,bar',
       'casualdining,pub', 'cafe,quickbites', 'lounge,bar',
       'bakery,quickbites', 'dessertparlor,quickbites',
       'bar,casualdining', 'beverageshop,dessertparlor',
       'casualdining,microbrewery', 'mess', 'lounge,casualdining',
       'cafe,dessertparlor', 'dessertparlor,cafe', 'bakery,dessertparlor',
       'quickbites,sweetshop', 'takeaway', 'microbrewery,pub', 'club',
       'finedining', 'bakery,cafe', 'beverageshop,cafe', 'pub,cafe',
       'casualdining,iranicafee', 'foodcourt,quickbites',
       'quickbites,beverageshop', 'finedining,lounge',
       'quickbites,bakery', 'bar,quickbites', 'pub,microbrewery',
       'microbrewery,lounge', 'finedining,microbrewery', 'finedining,bar',
       'dessertparlor,kiosk', 'cafe,bar', 'quickbites,foodcourt',
       'casualdining,lounge', 'microbrewery,bar', 'cafe,lounge',
       'bar,pub', 'lounge,cafe', 'dessertparlor,bakery',
       'club,casualdining', 'lounge,microbrewery', 'dhaba', 'bar,lounge',
       'foodcourt,casualdining'], dtype=object)

In [ ]:
df.rest_type.value_counts()

rest_type
casualdining               7349
quickbites                 5240
cafe                       2325
dessertparlor              1076
casualdining,bar            984
                           ...
finedining,microbrewery       5
club,casualdining             4
dessertparlor,kiosk           2
dhaba                         1
foodcourt,casualdining        1
Name: count, Length: 73, dtype: int64

In [ ]:
df.rest_type.isnull().sum()

np.int64(0)

In [ ]:
df.rest_type.describe()

count            23193
unique              73
top       casualdining
freq              7349
Name: rest_type, dtype: object

In [ ]:
df.dish_liked

0        Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
1        Momos, Lunch Buffet, Chocolate Nirvana, Thai G...
2        Churros, Cannelloni, Minestrone Soup, Hot Choc...
3                                              Masala Dosa
4                                      Panipuri, Gol Gappe
                               ...
23188    Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...
23189                                     Rooftop Ambience
23190    Salads, Coffee, Breakfast Buffet, Halwa, Chick...
23191                                 Biryani, Andhra Meal
23192                         Cocktails, Pizza, Buttermilk
Name: dish_liked, Length: 23193, dtype: object

In [ ]:
df.dish_liked=df.dish_liked.str.lower().str.replace(' ','_')

In [ ]:
df.dish_liked.unique()

array(['pasta,_lunch_buffet,_masala_papad,_paneer_lajawab,_tomato_shorba,_dum_biryani,_sweet_corn_soup',
       'momos,_lunch_buffet,_chocolate_nirvana,_thai_green_curry,_paneer_tikka,_dum_biryani,_chicken_biryani',
       'churros,_cannelloni,_minestrone_soup,_hot_chocolate,_pink_sauce_pasta,_salsa,_veg_supreme_pizza',
       ...,
       'noodles,_chicken_noodle,_momos,_american_chopsuey,_salad,_manchow_soup,_manchurian',
       'chicken_quesadilla,_naan,_breakfast_buffet,_cheesecake,_cocktails,_lunch_buffet,_biryani',
       'biryani,_andhra_meal'], dtype=object)

In [ ]:

df.dish_liked.value_counts()

dish_liked
biryani                                                                                     181
chicken_biryani                                                                              73
friendly_staff                                                                               69
waffles                                                                                      68
paratha                                                                                      57
                                                                                           ...
tandoori_chicken,_mutton_biryani,_butter_chicken                                              1
coffee,_raj_kachori,_idli,_vada,_tea,_masala_dosa,_chaat                                      1
masala_dosa,_filter_coffee,_curd_rice                                                         1
dal_makhani,_galauti_kebab,_dum_biryani,_rasgulla,_fish,_garlic_kheer,_tandoori_broccoli      1
watermelon_juice,_malai_kulfi                                                                 1
Name: count, Length: 5189, dtype: int64

In [ ]:

df.dish_liked.isnull().sum()

np.int64(0)

In [ ]:

df.dish_liked.describe()

count       23193
unique       5189
top       biryani
freq          181
Name: dish_liked, dtype: object

In [ ]:
df.cuisines

0                     North Indian, Mughlai, Chinese
1                        Chinese, North Indian, Thai
2                             Cafe, Mexican, Italian
3                         South Indian, North Indian
4                           North Indian, Rajasthani
                            ...
23188       North Indian, Continental, Mediterranean
23189                                    Finger Food
23190             Chinese, Continental, North Indian
23191    Andhra, South Indian, Chinese, North Indian
23192                                    Finger Food
Name: cuisines, Length: 23193, dtype: object

In [ ]:
df.cuisines=df.cuisines.str.strip()
df.cuisines=df.cuisines.str.lower()
df.cuisines=df.cuisines.str.replace('_','')

In [ ]:
df['cuisines']=df['cuisines'].str.title()

In [ ]:
df.cuisines.unique()

array(['North Indian, Mughlai, Chinese', 'Chinese, North Indian, Thai',
       'Cafe, Mexican, Italian', ..., 'Andhra, Hyderabadi, Biryani',
       'Andhra, North Indian, South Indian', 'Thai, Chinese, Momos'],
      dtype=object)

In [ ]:
df['cuisines']

0                     North Indian, Mughlai, Chinese
1                        Chinese, North Indian, Thai
2                             Cafe, Mexican, Italian
3                         South Indian, North Indian
4                           North Indian, Rajasthani
                            ...
23188       North Indian, Continental, Mediterranean
23189                                    Finger Food
23190             Chinese, Continental, North Indian
23191    Andhra, South Indian, Chinese, North Indian
23192                                    Finger Food
Name: cuisines, Length: 23193, dtype: object

In [ ]:
df.cuisines.value_counts()

cuisines
North Indian                           1144
North Indian, Chinese                   777
South Indian                            359
Cafe                                    273
South Indian, North Indian, Chinese     233
                                       ...
Tibetan, Nepalese                         1
South Indian, Chettinad                   1
Andhra, Hyderabadi, Biryani               1
Andhra, North Indian, South Indian        1
Thai, Chinese, Momos                      1
Name: count, Length: 1687, dtype: int64

In [ ]:
df.cuisines.isnull().sum()

np.int64(0)

In [ ]:
df.cuisines.describe()

count            23193
unique            1687
top       North Indian
freq              1144
Name: cuisines, dtype: object

In [ ]:
df.cuisines.dtype

dtype('O')

In [ ]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'listed_in(type)', 'listed_in(city)',
       'mobile'],
      dtype='object')

In [ ]:
df['approx_cost(for two people)']

0          800
1          800
2          800
3          300
4          600
         ...
23188    1,200
23189    2,000
23190    1,200
23191      800
23192    2,500
Name: approx_cost(for two people), Length: 23193, dtype: object

In [ ]:
df['approx_cost(for two people)'].unique()

array(['800', '300', '600', '700', '550', '500', '450', '650', '400',
       '750', '200', '850', '1,200', '150', '350', '250', '1,500',
       '1,300', '1,000', '100', '900', '1,100', '1,600', '950', '230',
       '1,700', '1,400', '1,350', '2,200', '2,000', '1,800', '1,900',
       '180', '330', '2,500', '2,100', '3,000', '2,800', '3,400', '40',
       '1,250', '3,500', '4,000', '2,400', '1,450', '3,200', '6,000',
       '1,050', '4,100', '2,300', '120', '2,600', '5,000', '3,700',
       '1,650', '2,700', '4,500'], dtype=object)

In [ ]:
df['approx_cost(for two people)']=df['approx_cost(for two people)'].str.replace(',','')

In [ ]:
df['approx_cost(for two people)']=df['approx_cost(for two people)'].astype(float)

In [ ]:
df['approx_cost(for two people)'].value_counts()

approx_cost(for two people)
400.0     2467
500.0     2271
600.0     2170
300.0     1688
800.0     1658
1000.0    1242
700.0     1160
1200.0     903
200.0      862
1500.0     858
450.0      720
250.0      697
750.0      652
650.0      637
350.0      553
900.0      518
1300.0     497
1100.0     462
1400.0     446
550.0      440
150.0      367
2000.0     297
1600.0     241
1700.0     233
1800.0     189
3000.0     159
2500.0     143
850.0      122
100.0      117
2100.0      63
1900.0      58
950.0       47
2200.0      39
2800.0      31
3500.0      25
4000.0      24
2400.0      22
1350.0      18
180.0       17
3400.0      13
230.0       10
1250.0       9
40.0         8
1650.0       6
1450.0       5
330.0        4
4100.0       4
2600.0       4
1050.0       4
3200.0       2
6000.0       2
2700.0       2
120.0        2
4500.0       2
2300.0       1
5000.0       1
3700.0       1
Name: count, dtype: int64

In [ ]:
df['approx_cost(for two people)'].dtype

dtype('float64')

In [ ]:
df['approx_cost(for two people)'].isnull().sum()

np.int64(0)

In [ ]:
df['approx_cost(for two people)'].describe()

count    23193.000000
mean       755.904368
std        521.448320
min         40.000000
25%        400.000000
50%        600.000000
75%       1000.000000
max       6000.000000
Name: approx_cost(for two people), dtype: float64

In [ ]:
df['listed_in(type)']

0               Buffet
1               Buffet
2               Buffet
3               Buffet
4               Buffet
             ...
23188    Pubs and bars
23189    Pubs and bars
23190    Pubs and bars
23191    Pubs and bars
23192    Pubs and bars
Name: listed_in(type), Length: 23193, dtype: object

In [ ]:
df['listed_in(type)']=df['listed_in(type)'].str.lower().str.replace(' ','')

In [ ]:
df['listed_in(type)'].unique()

array(['buffet', 'cafes', 'delivery', 'desserts', 'dine-out',
       'drinks&nightlife', 'pubsandbars'], dtype=object)

In [ ]:
df['listed_in(type)'].value_counts()

listed_in(type)
delivery            10625
dine-out             8009
desserts             1333
cafes                1047
drinks&nightlife      890
buffet                762
pubsandbars           527
Name: count, dtype: int64

In [ ]:
df['listed_in(type)'].isnull().sum()

np.int64(0)

In [ ]:
df['listed_in(type)'].describe()

count        23193
unique           7
top       delivery
freq         10625
Name: listed_in(type), dtype: object

In [ ]:
df['listed_in(city)']

0        Banashankari
1        Banashankari
2        Banashankari
3        Banashankari
4        Banashankari
             ...
23188      Whitefield
23189      Whitefield
23190      Whitefield
23191      Whitefield
23192      Whitefield
Name: listed_in(city), Length: 23193, dtype: object

In [ ]:

df['listed_in(city)']=df['listed_in(city)'].str.lower().str.replace(' ','')

In [ ]:
df['listed_in(city)'].unique()

array(['banashankari', 'bannerghattaroad', 'basavanagudi', 'bellandur',
       'brigaderoad', 'brookefield', 'btm', 'churchstreet',
       'electroniccity', 'frazertown', 'hsr', 'indiranagar', 'jayanagar',
       'jpnagar', 'kalyannagar', 'kammanahalli', 'koramangala4thblock',
       'koramangala5thblock', 'koramangala6thblock',
       'koramangala7thblock', 'lavelleroad', 'malleshwaram',
       'marathahalli', 'mgroad', 'newbelroad', 'oldairportroad',
       'rajajinagar', 'residencyroad', 'sarjapurroad', 'whitefield'],
      dtype=object)

In [ ]:
df['listed_in(city)'].value_counts()

listed_in(city)
btm                    1423
koramangala7thblock    1367
koramangala4thblock    1342
koramangala5thblock    1305
koramangala6thblock    1247
jayanagar              1048
indiranagar            1021
mgroad                 1015
churchstreet            979
brigaderoad             965
lavelleroad             897
residencyroad           843
jpnagar                 821
oldairportroad          748
hsr                     737
whitefield              630
marathahalli            621
basavanagudi            597
brookefield             595
bannerghattaroad        547
frazertown              545
kammanahalli            532
kalyannagar             519
bellandur               502
sarjapurroad            501
malleshwaram            492
rajajinagar             374
banashankari            372
electroniccity          326
newbelroad              282
Name: count, dtype: int64

In [ ]:
df['listed_in(city)'].isnull().sum()

np.int64(0)

In [ ]:
df['listed_in(city)'].dtype

dtype('O')

In [ ]:
df['listed_in(city)'].describe()

count     23193
unique       30
top         btm
freq       1423
Name: listed_in(city), dtype: object

In [ ]:
df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city),mobile
0,jalsa,yes,yes,4.1,775,08042297555919743772233,banashankari,casualdining,"pasta,_lunch_buffet,_masala_papad,_paneer_laja...","North Indian, Mughlai, Chinese",800.0,buffet,banashankari,9743772233
1,spice_elephant,yes,no,4.1,787,08041714161,banashankari,casualdining,"momos,_lunch_buffet,_chocolate_nirvana,_thai_g...","Chinese, North Indian, Thai",800.0,buffet,banashankari,8041714161
2,san_churro_cafe,yes,no,3.8,918,919663487993,banashankari,"cafe,casualdining","churros,_cannelloni,_minestrone_soup,_hot_choc...","Cafe, Mexican, Italian",800.0,buffet,banashankari,9663487993
3,addhuri_udupi_bhojana,no,no,3.7,88,919620009302,banashankari,quickbites,masala_dosa,"South Indian, North Indian",300.0,buffet,banashankari,9620009302
4,grand_village,no,no,3.8,166,918026612447919901210005,basavanagudi,casualdining,"panipuri,_gol_gappe","North Indian, Rajasthani",600.0,buffet,banashankari,9901210005

In [ ]:
df.shape

(23193, 14)

In [ ]:
df.drop(['phone'],axis=1,inplace=True)

In [ ]:
df.shape

(23193, 13)

In [ ]:
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city),mobile
0,jalsa,yes,yes,4.1,775,banashankari,casualdining,"pasta,_lunch_buffet,_masala_papad,_paneer_laja...","North Indian, Mughlai, Chinese",800.0,buffet,banashankari,9743772233
1,spice_elephant,yes,no,4.1,787,banashankari,casualdining,"momos,_lunch_buffet,_chocolate_nirvana,_thai_g...","Chinese, North Indian, Thai",800.0,buffet,banashankari,8041714161
2,san_churro_cafe,yes,no,3.8,918,banashankari,"cafe,casualdining","churros,_cannelloni,_minestrone_soup,_hot_choc...","Cafe, Mexican, Italian",800.0,buffet,banashankari,9663487993
3,addhuri_udupi_bhojana,no,no,3.7,88,banashankari,quickbites,masala_dosa,"South Indian, North Indian",300.0,buffet,banashankari,9620009302
4,grand_village,no,no,3.8,166,basavanagudi,casualdining,"panipuri,_gol_gappe","North Indian, Rajasthani",600.0,buffet,banashankari,9901210005

In [ ]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
23188    False
23189    False
23190    False
23191    False
23192    False
Length: 23193, dtype: bool

In [ ]:
df[df.duplicated()]

,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city),mobile
1532,the_fishermans_wharf,yes,yes,4.4,4099,sarjapur_road,"casualdining,bar","sea_food,_caesar_salad,_jumbo_prawns,_cocktail...","Seafood, Goan, North Indian, Continental, Asian",1400.0,buffet,bellandur,8049653108
1998,opus_club,no,yes,4.4,1496,sarjapur_road,pub,"biryani,_cocktails,_nachos,_mocktails,_long_is...","Continental, Italian, North Indian, Mexican",1900.0,drinks&nightlife,bellandur,7349734900
1999,float,yes,yes,4.4,3061,marathahalli,"casualdining,bar","butter_fish,_chicken_burritos,_cocktails,_mock...","North Indian, Japanese",1500.0,drinks&nightlife,bellandur,9066887086
2015,float,yes,yes,4.4,3061,marathahalli,"casualdining,bar","butter_fish,_chicken_burritos,_cocktails,_mock...","North Indian, Japanese",1500.0,pubsandbars,bellandur,9066887086
2887,fava,no,yes,4.4,2039,lavelle_road,"casualdining,bar","gnocchi,_cocktails,_pizza,_salads,_creme_brule...","Healthy Food, Mediterranean, Desserts, Italian...",1200.0,drinks&nightlife,brigaderoad,8049652925
4243,vyanjan,yes,no,3.9,201,btm,quickbites,"poha,_jalebi,_paratha,_bhindi_masala,_kachori,...","North Indian, Street Food",300.0,delivery,btm,9916937446
4244,mid_night_hunting,yes,no,3.7,127,ejipura,"takeaway,delivery","burgers,_chicken_burger,_pasta,_chicken_pizza","Fast Food, Italian",300.0,delivery,btm,8892140430
4245,carrots,yes,yes,4.1,600,koramangala_6th_block,casualdining,"pizza,_pasta,_salads,_masala_chai,_soya_butter...","Italian, North Indian, Healthy Food, Desserts",1100.0,delivery,btm,8041172812
4246,rolls_&_co,yes,no,3.9,213,koramangala_6th_block,quickbites,"rolls,_chicken_wings,_shawarma,_chicken_tikka_...","Burger, Beverages, Rolls",400.0,delivery,btm,7353848635
4973,fennys_lounge_and_kitchen,no,yes,4.5,6349,koramangala_7th_block,"bar,casualdining","caramel_pudding,_cocktails,_pizza,_mocktails,_...","Mediterranean, Pizza, Continental, Seafood, Salad",1600.0,pubsandbars,btm,8049653085
5390,corner_house_ice_cream,yes,no,4.4,635,residency_road,dessertparlor,"hot_chocolate_fudge,_chocolate_mousse,_ice_cre...","Ice Cream, Desserts",400.0,delivery,churchstreet,9900545172
5392,taaam,yes,no,4.1,402,cunningham_road,casualdining,"laham_mandi,_mutton_chops,_biryani,_mutton_sou...","North Indian, Mughlai, Arabian, Chinese",750.0,delivery,churchstreet,9845538446
5401,laughing_llama_gastropub,yes,yes,4.3,394,brigade_road,"bar,casualdining","pancakes,_cocktails,_biryani,_draught_beer,_lo...","Finger Food, Continental, Pizza",1600.0,delivery,churchstreet,9535029732
5402,the_bundle_co,yes,no,4.4,223,mg_road,quickbites,"burgers,_salad,_mocktails,_pasta_arrabiata,_fr...","Burger, Continental, Italian, Beverages",700.0,delivery,churchstreet,9148887222
5404,vietnamese_kitchen,yes,yes,4.1,525,indiranagar,casualdining,"pho,_pad_thai,_jasmine_tea,_spring_roll,_choco...","Chinese, Vietnamese, Momos, Thai",800.0,delivery,churchstreet,8041566009
5407,the_yogisthaan_cafe,yes,no,4.2,1207,indiranagar,cafe,"salads,_sandwich,_pasta,_tea,_hot_chocolate,_p...","Cafe, Healthy Food, Salad, Beverages",600.0,delivery,churchstreet,7411400888
5410,moto_store_&_caf,yes,no,4.2,382,ulsoor,cafe,"wedges,_maggi,_burgers,_waffles,_margherita_pi...","Pizza, Italian, Cafe, Burger, Finger Food, Fas...",500.0,delivery,churchstreet,8049653126
5411,hoppipola,yes,no,4.3,1708,church_street,lounge,"masala_peanuts,_cocktails,_paratha,_pizza,_pas...","Continental, Mediterranean, European",1300.0,delivery,churchstreet,9620216162
5415,the_only_place,yes,yes,4.2,2924,church_street,casualdining,"steak,_burgers,_meatballs,_apple_pie,_salads,_...","Italian, American, Steak, Continental, Bbq, Salad",1000.0,delivery,churchstreet,9986011113
5417,99_pancakes,yes,no,4.1,41,church_street,dessertparlor,nutella_pancakes,"Desserts, Ice Cream",150.0,delivery,churchstreet,7483655827
5418,nolimmits_lounge_and_club,yes,yes,4.0,2112,brigade_road,club,"salads,_chicken_bbq_wings,_sandwiches,_pasta,_...","Chinese, Continental, North Indian, Burger, Pizza",2000.0,delivery,churchstreet,8049653274
5421,toscano,yes,yes,4.4,1842,lavelle_road,casualdining,"pizza,_pepperoni,_wine,_salads,_tiramisu,_chic...","Italian, Salad",1500.0,delivery,churchstreet,7619320071
5422,the_biere_club,yes,yes,4.3,3485,lavelle_road,"pub,microbrewery","wheat_beer,_pizza,_cocktails,_virgin_sangria,_...","Continental, Bbq, Finger Food",1700.0,delivery,churchstreet,8042134668
6021,lassi_adda,yes,no,4.0,65,electronic_city,beverageshop,"sweet_lassi,_corn_sandwich","Beverages, Sandwich, Fast Food",200.0,delivery,electroniccity,9986382545
7282,cinnamon,yes,no,3.9,450,hsr,casualdining,"raita,_tandoori_chicken,_egg_chilli,_hakka_noo...","North Indian, Chinese, Biryani",550.0,delivery,hsr,8041201897
8174,sly_granny__the_community_house,no,yes,4.4,953,indiranagar,"finedining,bar","cocktails,_pie,_rolls,_mezze_platter,_schnitze...","Modern Indian, European, American",2500.0,dine-out,indiranagar,8048536715
8900,toscano,yes,yes,4.5,715,koramangala_7th_block,casualdining,"pizza,_pasta,_cocktails,_spinach_ravioli,_tira...","Italian, Salad",1500.0,delivery,jayanagar,7619320075
9085,funky_punjab,yes,no,3.8,125,btm,quickbites,"roti,_dal_makhani,_lassi,_panneer_butter_masal...","North Indian, Chinese",400.0,delivery,jayanagar,8884449474
10763,victoria_terminus,yes,no,2.9,54,banaswadi,quickbites,"vada_pav,_kulfi,_mumbai_sandwich,_rolls,_keema...","Fast Food, Maharashtrian, Rolls",250.0,delivery,kalyannagar,9066157771
13688,chinita_real_mexican_food,no,no,4.5,733,koramangala_5th_block,casualdining,"tacos,_churros,_nachos,_salad,_enchiladas,_bur...",Mexican,1200.0,dine-out,koramangala5thblock,8043711400
13846,154_breakfast_club,yes,yes,4.0,1515,koramangala_3rd_block,cafe,"pancakes,_waffles,_bbq_sandwich,_mushroom_rago...","Cafe, Continental",900.0,dine-out,koramangala5thblock,8025533133
16820,the_oriental_spice__ashraya_hotel,yes,no,3.9,158,infantry_road,casualdining,"noodles,_lunch_buffet,_fish,_manchurian,_salad...","Chinese, Thai, Indonesian",1300.0,buffet,lavelleroad,7795612130
17253,rasovara,yes,yes,4.3,772,lavelle_road,casualdining,"thali,_aamras,_malpua,_dal_bati,_lassi,_plain_...","Rajasthani, North Indian",1400.0,dine-out,lavelleroad,9886060965
18575,sizzling_pasto,yes,yes,4.1,99,marathahalli,"casualdining,bar","mocktails,_brownie,_sangria,_cocktail_prawn,_s...","Continental, Chinese, North Indian",1100.0,dine-out,marathahalli,8049652891
18931,red_onion,yes,yes,4.2,570,shanti_nagar,casualdining,"fish,_dumplings,_biryani,_paneer_tikka_masala,...","Chinese, North Indian, Biryani, Kebab",1200.0,delivery,mgroad,8867785004
19487,bootlegger,no,no,4.1,1545,lavelle_road,pub,"beer,_cocktails,_beef_steak,_beef_chilli,_nach...","Continental, Steak",1200.0,dine-out,mgroad,8041462747
19501,ithaca__the_chancery_pavilion,no,yes,3.9,312,residency_road,finedining,"salads,_sunday_brunch,_cocktails,_watermelon_j...","North Indian, Italian, European, Continental",2000.0,dine-out,mgroad,9902785566
19718,alchemy__the_chancery_pavilion,no,yes,4.3,485,residency_road,"microbrewery,casualdining","craft_beer,_cocktails,_stout,_chicken_wings,_f...",Modern Indian,2000.0,drinks&nightlife,mgroad,8049653555
20785,tipsy_bull__the_bar_exchange,no,yes,4.6,3173,indiranagar,"bar,casualdining","cocktails,_peri_peri_chicken,_biryani,_mocktai...","Chinese, Continental, North Indian, Mexican",1400.0,drinks&nightlife,oldairportroad,8049652910
20786,btdt_been_there_done_that,no,yes,4.3,962,indiranagar,"bar,casualdining","cocktails,_momos,_pizza,_mushroom_ragout,_roti...","European, Continental, Asian, Finger Food",1300.0,drinks&nightlife,oldairportroad,8049652655
22014,shakesbierre,no,yes,4.4,409,brigade_road,"microbrewery,casualdining","cocktails,_mocktails,_pizza,_sweet_yogurt,_juj...","Asian, Continental, European, North Indian",1500.0,drinks&nightlife,residencyroad,8049653253

In [ ]:
df.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
mobile                         0
dtype: int64

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(23152, 13)

In [ ]:

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23152 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23152 non-null  object
 1   online_order                 23152 non-null  object
 2   book_table                   23152 non-null  object
 3   rate                         23152 non-null  float64
 4   votes                        23152 non-null  int64
 5   location                     23152 non-null  object
 6   rest_type                    23152 non-null  object
 7   dish_liked                   23152 non-null  object
 8   cuisines                     23152 non-null  object
 9   approx_cost(for two people)  23152 non-null  float64
 10  listed_in(type)              23152 non-null  object
 11  listed_in(city)              23152 non-null  object
 12  mobile                       23152 non-null  int64
dtypes: float64(2), int64(2), object(9)
memory usage: 2.5+ MB

In [ ]:
df.describe()

               rate         votes  approx_cost(for two people)        mobile
count  23152.000000  23152.000000                 23152.000000  2.315200e+04
mean       3.904557    599.969722                   755.251814  8.580773e+09
std        0.426512   1114.085993                   521.115035  9.831955e+08
min        1.800000      0.000000                    40.000000  2.286364e+07
25%        3.800000    101.000000                   400.000000  8.041104e+09
50%        4.000000    221.000000                   600.000000  8.049716e+09
75%        4.200000    584.000000                  1000.000000  9.599699e+09
max        4.900000  16832.000000                  6000.000000  9.999266e+09

In [ ]:
#df.sort_values('rate', ascending=False).head(10)

In [ ]:
#df[['rate', 'approx_cost(for two people)']].corr()

In [ ]:
#df.groupby('location')['rate'].mean().sort_values(ascending=False)

In [ ]:
#df.groupby('online_order')['rate'].mean()

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df.to_csv('cleaned_data_fixed.csv', index=False, quoting=1)

In [ ]:
df.to_csv('cleaned_data.csv', index=False, encoding='utf-8',quoting=1)

In [ ]:
import os

In [ ]:
print(os.getcwd())

/content